import { lazy } from 'react';
import __Layout from './Layout.jsx';


export const PAGES = {
    "AccountSettings": lazy(() => import('./pages/AccountSettings')),
    "ArtCollectibles": lazy(() => import('./pages/ArtCollectibles')),
    "AuditLog": lazy(() => import('./pages/AuditLog')),
    "AutomatedPayments": lazy(() => import('./pages/AutomatedPayments')),
    "Automations": lazy(() => import('./pages/Automations')),
    "BillPayments": lazy(() => import('./pages/BillPayments')),
    "Budget": lazy(() => import('./pages/Budget')),
    "BusinessClients": lazy(() => import('./pages/BusinessClients')),
    "BusinessContracts": lazy(() => import('./pages/BusinessContracts')),
    "BusinessExpenses": lazy(() => import('./pages/BusinessExpenses')),
    "BusinessHub": lazy(() => import('./pages/BusinessHub')),
    "BusinessInvoices": lazy(() => import('./pages/BusinessInvoices')),
    "BusinessProjects": lazy(() => import('./pages/BusinessProjects')),
    "BusinessReports": lazy(() => import('./pages/BusinessReports')),
    "CaregiverCoordination": lazy(() => import('./pages/CaregiverCoordination')),
    "CharitableGiving": lazy(() => import('./pages/CharitableGiving')),
    "ClientDashboard": lazy(() => import('./pages/ClientDashboard')),
    "Collaboration": lazy(() => import('./pages/Collaboration')),
    "CommunicationsHub": lazy(() => import('./pages/CommunicationsHub')),
    "ConciergeService": lazy(() => import('./pages/ConciergeService')),
    "Contacts": lazy(() => import('./pages/Contacts')),
    "Dashboard": lazy(() => import('./pages/Dashboard')),
    "DigitalMemorial": lazy(() => import('./pages/DigitalMemorial')),
    "DoctorAppointments": lazy(() => import('./pages/DoctorAppointments')),
    "EducationFunds": lazy(() => import('./pages/EducationFunds')),
    "EmailAssistant": lazy(() => import('./pages/EmailAssistant')),
    "EmergencyResponse": lazy(() => import('./pages/EmergencyResponse')),
    "EstatePlanning": lazy(() => import('./pages/EstatePlanning')),
    "FAQ": lazy(() => import('./pages/FAQ')),
    "FamilyManagement": lazy(() => import('./pages/FamilyManagement')),
    "FamilyNotifications": lazy(() => import('./pages/FamilyNotifications')),
    "FamilyRoleManagement": lazy(() => import('./pages/FamilyRoleManagement')),
    "FamilyToDo": lazy(() => import('./pages/FamilyToDo')),
    "FamilyTree": lazy(() => import('./pages/FamilyTree')),
    "FamilyWorkflows": lazy(() => import('./pages/FamilyWorkflows')),
    "FinancialDashboard": lazy(() => import('./pages/FinancialDashboard')),
    "FinancialForecasting": lazy(() => import('./pages/FinancialForecasting')),
    "FinancialHealth": lazy(() => import('./pages/FinancialHealth')),
    "FinancialLiteracy": lazy(() => import('./pages/FinancialLiteracy')),
    "FinancialProfile": lazy(() => import('./pages/FinancialProfile')),
    "Health": lazy(() => import('./pages/Health')),
    "Home": lazy(() => import('./pages/Home')),
    "HomeInventory": lazy(() => import('./pages/HomeInventory')),
    "HomeServices": lazy(() => import('./pages/HomeServices')),
    "Integrations": lazy(() => import('./pages/Integrations')),
    "InternationalAssets": lazy(() => import('./pages/InternationalAssets')),
    "Investments": lazy(() => import('./pages/Investments')),
    "LegacyMessages": lazy(() => import('./pages/LegacyMessages')),
    "Legal": lazy(() => import('./pages/Legal')),
    "Maintenance": lazy(() => import('./pages/Maintenance')),
    "MedicalProfile": lazy(() => import('./pages/MedicalProfile')),
    "MedicareNavigator": lazy(() => import('./pages/MedicareNavigator')),
    "NotificationSettings": lazy(() => import('./pages/NotificationSettings')),
    "Pricing": lazy(() => import('./pages/Pricing')),
    "Privacy": lazy(() => import('./pages/Privacy')),
    "ProfessionalMarketplace": lazy(() => import('./pages/ProfessionalMarketplace')),
    "Properties": lazy(() => import('./pages/Properties')),
    "PropertyManagement": lazy(() => import('./pages/PropertyManagement')),
    "Reports": lazy(() => import('./pages/Reports')),
    "RoleManagement": lazy(() => import('./pages/RoleManagement')),
    "SecurityAudit": lazy(() => import('./pages/SecurityAudit')),
    "Subscriptions": lazy(() => import('./pages/Subscriptions')),
    "Succession": lazy(() => import('./pages/Succession')),
    "TaxExport": lazy(() => import('./pages/TaxExport')),
    "TenantPortal": lazy(() => import('./pages/TenantPortal')),
    "Terms": lazy(() => import('./pages/Terms')),
    "Travel": lazy(() => import('./pages/Travel')),
    "TrustManagement": lazy(() => import('./pages/TrustManagement')),
    "Valuables": lazy(() => import('./pages/Valuables')),
    "Vault": lazy(() => import('./pages/Vault')),
    "Vehicles": lazy(() => import('./pages/Vehicles')),
    "VideoCallScheduler": lazy(() => import('./pages/VideoCallScheduler')),
    "VideoTutorials": lazy(() => import('./pages/VideoTutorials')),
    "VoiceAssistant": lazy(() => import('./pages/VoiceAssistant')),
    "WealthLegacyPlanning": lazy(() => import('./pages/WealthLegacyPlanning')),
    "Calendar": lazy(() => import('./pages/Calendar')),
}

export const pagesConfig = {
    mainPage: "Vault",
    Pages: PAGES,
    Layout: __Layout,
};